// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvlsvujqzxcouqbfzndc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bHN2dWpxenhjb3VxYmZ6bmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTAxNTksImV4cCI6MjA2OTU4NjE1OX0.99Zkt81_rRsav3v7fTAMRD5o3Jejz_CA4-ljvSLuB5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});